apiVersion: v1
kind: Pod
metadata:
  name: golinks
spec:
  containers:
    - image: ghcr.io/karlcaga/go-psql-golinks:main
      name: golinks
      env:
        - name: CONN_STR
          value: <INSERT CONNECTION STRING HERE>
      resources:
        requests:
          cpu: "100m"
          memory: "64Mi"
        limits:
          cpu: "250m"
          memory: "128Mi"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
